package org.example.trademodel.derivatives;

public enum DerivativesEvidenceType {
    OPEN_INTEREST_EXPANSION,
    OPEN_INTEREST_CONTRACTION,
    OPEN_INTEREST_PRICE_CONFIRMATION,
    OPEN_INTEREST_PRICE_DIVERGENCE,
    FUNDING_POSITIVE_EXTREME,
    FUNDING_NEGATIVE_EXTREME,
    FUNDING_NORMAL,
    LONG_CROWDING,
    SHORT_CROWDING,
    LONG_LIQUIDATION_SPIKE,
    SHORT_LIQUIDATION_SPIKE,
    LIQUIDATION_IMBALANCE,
    EXCHANGE_CONCENTRATION_HIGH,
    DERIVATIVES_DATA_PARTIAL,
    DERIVATIVES_DATA_STALE,
    DERIVATIVES_DATA_UNAVAILABLE
}
