package org.example.trademodel.providercall.ai;

public enum AiCheckpoint {
    ENTERED_CANDIDATE,
    ENTERED_WAITING_TRIGGER,
    ENTERED_TRIGGERED,
    DIRECTION_CHANGED,
    CONFIDENCE_MATERIALLY_CHANGED,
    RISK_INCREASED,
    CONFUSED_SCORE_INCREASED,
    HOT_RESET,
    PUSH_RECHECK,
    POSITION_LOGIC_WEAKENED,
    POSITION_PLAN_INVALIDATED,
    STRONG_REVERSAL,
    MATERIAL_NEWS_EVENT
}
