#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Thu Apr 16 17:19:31 CST 2026
maven-metadata-nexus-tencentyun.xml.lastUpdated=1776331171292
