package org.example.trademodel.ai;

public enum AiProviderControlledSmokeStatus {
    PASS,
    SKIPPED_EXTERNAL_CALLS_DISABLED,
    SKIPPED_HARNESS_ENTRY_MISSING,
    SKIPPED_MISSING_API_KEY,
    SKIPPED_PROVIDER_DISABLED,
    FAIL_INVALID_TARGET,
    FAIL_AUTH,
    FAIL_BILLING_OR_CREDITS,
    FAIL_MODEL_NOT_FOUND,
    FAIL_RATE_LIMIT,
    FAIL_TIMEOUT,
    FAIL_RESPONSE_SCHEMA,
    FAIL_PROVIDER_HTTP,
    FAIL_PROVIDER_IO,
    FAIL_UNEXPECTED
}
