package org.example.trademodel.ai;

public enum AiProviderErrorReason {
    GEMINI_HTTP_400_INVALID_REQUEST,
    GEMINI_STRUCTURED_OUTPUT_UNSUPPORTED,
    GEMINI_MODEL_CAPABILITY_ERROR,
    GEMINI_AUTH_REJECTED,
    GEMINI_RATE_LIMITED,
    GEMINI_HTTP_5XX_INTERNAL,
    GEMINI_UNKNOWN_PROVIDER_ERROR
}
