package org.example.trademodel.ai;

/** Sanitized fail-closed reasons for the Gemini Interactions response contract. */
public enum GeminiInteractionFailureReason {
    GEMINI_INTERACTION_STATUS_IN_PROGRESS,
    GEMINI_INTERACTION_STATUS_REQUIRES_ACTION,
    GEMINI_INTERACTION_STATUS_FAILED,
    GEMINI_INTERACTION_STATUS_CANCELLED,
    GEMINI_INTERACTION_STATUS_INCOMPLETE,
    GEMINI_INTERACTION_STATUS_MISSING,
    GEMINI_INTERACTION_MODEL_OUTPUT_MISSING,
    GEMINI_INTERACTION_FINAL_TEXT_MISSING,
    GEMINI_INTERACTION_FINAL_JSON_INVALID,
    GEMINI_INTERACTION_V1_CONTRACT_INVALID,
    GEMINI_INTERACTION_RESPONSE_ENVELOPE_INVALID
}
