package org.example.trademodel.dto.ohlcv;

public enum PublicProviderErrorCode {
    HTTP_401,
    HTTP_403,
    HTTP_429,
    HTTP_451,
    HTTP_5XX,
    TIMEOUT,
    DNS_FAILURE,
    INVALID_RESPONSE,
    PAIR_NOT_SUPPORTED,
    REGION_RESTRICTED,
    GEO_RESTRICTED,
    RATE_LIMITED,
    PROVIDER_UNAVAILABLE,
    PROVIDER_UNAVAILABLE_FOR_LOCATION,
    KRAKEN_PAIR_RESOLUTION_ERROR,
    KRAKEN_OHLC_UNKNOWN_PAIR,
    INVALID_SYMBOL_MAPPING,
    INTERNAL_MAPPING_ERROR
}
