#!/usr/bin/env bash
set -euo pipefail

input_file="${1:-}"
output_file="${2:-}"
if [ -z "${input_file}" ] || [ -z "${output_file}" ] \
    || [ ! -f "${input_file}" ] || [ -L "${input_file}" ]; then
  echo "P3H_LAB_EVIDENCE_REDACTION: BLOCKED_INPUT" >&2
  exit 2
fi

umask 077
mkdir -p "$(dirname "${output_file}")"
awk -F ': ' '
  BEGIN {
    split("P3H_REMOTE_STAGE SOURCE_ARCHIVE_SHA256 SOURCE_ARCHIVE_REMOTE_SHA256 APP_IMAGE_REVISION REMOTE_PREFLIGHT LINUX_DISTRIBUTION KERNEL_RELEASE CPU_ARCHITECTURE SYSTEMD_VERSION DOCKER_ENGINE_VERSION DOCKER_COMPOSE_VERSION OPENSSL_VERSION TIMEZONE TIME_SYNCHRONIZED SECRET_BACKEND_CLASS SECRET_MOUNT SECRET_MOUNT_RUNTIME_VERIFICATION SECRET_MOUNT_FILESYSTEM SECRET_FILE_CONTRACT SUDO_NONINTERACTIVE STAGING_FLYWAY FLYWAY_REPEAT APPLICATION_DATABASE_ROLE READ_ONLY_WRITE_PROBE TLS_1_2 TLS_1_3 HTTP_TO_HTTPS_REDIRECT UNKNOWN_HOST UNAUTHENTICATED_API AUTHENTICATED_DASHBOARD EMPTY_DASHBOARD_FAIL_CLOSED RATE_LIMIT PROD_BACKUP_SCRIPT PROD_RESTORE_SCRIPT RESTORE_SCHEMA RESTORE_CONTENT ADMIN_SECRET_ROTATION DATABASE_SECRET_ROTATION TLS_ROTATION SERVICE_RESTART VM_REBOOT_STATUS V2_DATABASE_AFTER_REBOOT V1_DATABASE_AFTER_REBOOT V2_ADMIN_AFTER_REBOOT V1_ADMIN_AFTER_REBOOT POST_REBOOT_CONTENT_FINGERPRINT SECRET_LEAK_CANDIDATE_COUNT PROVIDER_EXTERNAL_CALLS AI_EXTERNAL_CALLS SCHEDULERS TRADING P3H_REMOTE_EXECUTION_IMPLEMENTATION REAL_EXTERNAL_STAGING_STATUS P3H_RESULT P4_ALLOWED PRODUCTION_READINESS", keys, " ")
    for (i in keys) allowed[keys[i]] = 1
  }
  NF == 2 && allowed[$1] && $2 ~ /^[A-Za-z0-9._,+-]+$/ { print $1 ": " $2 }
' "${input_file}" >"${output_file}"

for required_line in \
    'STAGING_FLYWAY: PASS_V1_TO_V7' \
    'APPLICATION_DATABASE_ROLE: READ_ONLY' \
    'READ_ONLY_WRITE_PROBE: DENIED' \
    'SECRET_LEAK_CANDIDATE_COUNT: 0' \
    'P4_ALLOWED: NO' \
    'PRODUCTION_READINESS: BLOCKED'; do
  grep -Fxq "${required_line}" "${output_file}" \
    || { echo "P3H_LAB_EVIDENCE_REDACTION: BLOCKED_INCOMPLETE" >&2; exit 2; }
done

if grep -Eiq '(BEGIN (RSA |EC |OPENSSH )?PRIVATE KEY|password=|api[_-]?key=|Bearer[[:space:]])' \
    "${output_file}"; then
  echo "P3H_LAB_EVIDENCE_REDACTION: BLOCKED_SECRET_PATTERN" >&2
  exit 2
fi
echo "P3H_LAB_EVIDENCE_REDACTION: PASS"

