package org.example.trademodel.postgresql;

import org.junit.jupiter.api.Test;
import org.springframework.core.io.ClassPathResource;
import org.springframework.jdbc.datasource.init.ScriptUtils;

import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

class V19UserPositionSubmissionIdempotencyMigrationContractTest {
    private static final Path MIGRATION = Path.of(
            "src/main/resources/db/migration/V19__user_position_submission_idempotency.sql");

    @Test
    void migrationAddsOwnerScopedKeysWithoutRewritingOrDeletingHistoricalPositions() throws Exception {
        String sql = Files.readString(MIGRATION);

        assertThat(sql).contains(
                        "ADD COLUMN submission_id VARCHAR(128)",
                        "ADD COLUMN close_submission_id VARCHAR(128)",
                        "ON tm_user_position(user_id, submission_id)",
                        "ON tm_user_position(user_id, close_submission_id)",
                        "historical rows remain null")
                .doesNotContainIgnoringCase("DELETE FROM tm_user_position")
                .doesNotContainIgnoringCase("UPDATE tm_user_position");
    }

    @Test
    void h2ExecutesV19PreservesLegacyRowsAndEnforcesOwnerScopedUniqueness() throws Exception {
        try (Connection connection = DriverManager.getConnection(
                "jdbc:h2:mem:v19-user-position;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1",
                "sa", "")) {
            connection.createStatement().execute("""
                    CREATE TABLE tm_user_position(
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        user_id BIGINT,
                        asset_symbol VARCHAR(32) NOT NULL
                    )
                    """);
            connection.createStatement().execute(
                    "INSERT INTO tm_user_position(user_id, asset_symbol) VALUES (41, 'ETHUSDT'), (41, 'ETHUSDT')");

            ScriptUtils.executeSqlScript(connection,
                    new ClassPathResource("db/migration/V19__user_position_submission_idempotency.sql"));

            assertThat(count(connection)).isEqualTo(2);
            insert(connection, 41L, "open:owner-41", "close:owner-41");
            insert(connection, 42L, "open:owner-41", "close:owner-41");
            assertThat(count(connection)).isEqualTo(4);
            assertThatThrownBy(() -> insert(connection, 41L, "open:owner-41", "close:other"))
                    .isInstanceOf(SQLException.class);
            assertThatThrownBy(() -> insert(connection, 41L, "open:other", "close:owner-41"))
                    .isInstanceOf(SQLException.class);
        }
    }

    private static void insert(Connection connection, Long userId,
                               String submissionId, String closeSubmissionId) throws Exception {
        try (PreparedStatement statement = connection.prepareStatement("""
                INSERT INTO tm_user_position(user_id, submission_id, close_submission_id, asset_symbol)
                VALUES (?, ?, ?, 'ETHUSDT')
                """)) {
            statement.setLong(1, userId);
            statement.setString(2, submissionId);
            statement.setString(3, closeSubmissionId);
            statement.executeUpdate();
        }
    }

    private static int count(Connection connection) throws Exception {
        try (ResultSet result = connection.createStatement().executeQuery(
                "SELECT COUNT(*) FROM tm_user_position")) {
            assertThat(result.next()).isTrue();
            return result.getInt(1);
        }
    }
}
