CREATE TABLE IF NOT EXISTS tm_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    last_login_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT uq_tm_user_username UNIQUE (username)
);

COMMENT ON TABLE tm_user IS
    'Single-person authentication identity for server-side session login.';

COMMENT ON COLUMN tm_user.password_hash IS
    'BCrypt password hash. Plaintext credentials are never persisted.';

COMMENT ON COLUMN tm_user.created_at IS
    'Application-written UTC-naive creation time.';

COMMENT ON COLUMN tm_user.last_login_at IS
    'Application-written UTC-naive time of the latest successful authentication.';
